version: "3"

services:

  postgres:
    image: postgres:9.6

    container_name: postgres

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea

    networks:
      - internal
      - host_out

    volumes:
      - /opt/data/sql:/var/lib/postgresql/data

  nginx:
    image: nginx

    container_name: nginx

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/www:/var/www
      - /opt/data/nginx:/etc/nginx

    networks:
      - internal
      - host_out
      
    depends_on:
      - gitea

  gitea:
    image: gitea/gitea:latest

    container_name: gitea

    environment:
      - USER_UID=1000
      - USER_GID=1000
    
    restart: always

    networks:
      - internal

    volumes:
      - /opt/data/gitea:/data

    ports:
      - "3000"
      - "22"

    depends_on:
      - postgres

networks:
  host_out:         
  internal:
    